name = "vvault-accounts"
main = "worker.js"
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "DB"
database_name = "vvault"
database_id = "PUT_YOUR_D1_DATABASE_ID_HERE"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "vvault-backups"
